module(
    name = "cpp_argon_demo",
    version = "4.0.1",
)

git_repository = use_repo_rule("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

git_repository(
    name = "cpp-argon",
    remote = "https://github.com/SpectraL519/cpp-argon.git",
    branch = "doc-gen-alignment",
)

bazel_dep(name = "rules_cc", version = "0.2.25")
